require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/*
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130
  AllowURI: true
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/AbcSize:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
